
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CLASS COLON COMMA IDENTIFIER LPAREN OTHER RPARENprogram : segment_listsegment_list : segment_list segment\n                    | segmentsegment : class_def\n               | miscclass_def : CLASS IDENTIFIER inheritance_opt COLONinheritance_opt : LPAREN base_classes RPAREN\n                       | emptybase_classes : IDENTIFIER base_class_tailbase_class_tail : COMMA IDENTIFIER base_class_tail\n                       | emptymisc : IDENTIFIER\n            | OTHERempty :'
    
_lr_action_items = {'CLASS':([0,2,3,4,5,7,8,9,14,],[6,6,-3,-4,-5,-12,-13,-2,-6,]),'IDENTIFIER':([0,2,3,4,5,6,7,8,9,12,14,19,],[7,7,-3,-4,-5,10,-12,-13,-2,16,-6,21,]),'OTHER':([0,2,3,4,5,7,8,9,14,],[8,8,-3,-4,-5,-12,-13,-2,-6,]),'$end':([1,2,3,4,5,7,8,9,14,],[0,-1,-3,-4,-5,-12,-13,-2,-6,]),'LPAREN':([10,],[12,]),'COLON':([10,11,13,17,],[-14,14,-8,-7,]),'RPAREN':([15,16,18,20,21,22,],[17,-14,-9,-11,-14,-10,]),'COMMA':([16,21,],[19,19,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'segment_list':([0,],[2,]),'segment':([0,2,],[3,9,]),'class_def':([0,2,],[4,4,]),'misc':([0,2,],[5,5,]),'inheritance_opt':([10,],[11,]),'empty':([10,16,21,],[13,20,20,]),'base_classes':([12,],[15,]),'base_class_tail':([16,21,],[18,22,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> segment_list','program',1,'p_program','parser.py',43),
  ('segment_list -> segment_list segment','segment_list',2,'p_segment_list','parser.py',47),
  ('segment_list -> segment','segment_list',1,'p_segment_list','parser.py',48),
  ('segment -> class_def','segment',1,'p_segment','parser.py',55),
  ('segment -> misc','segment',1,'p_segment','parser.py',56),
  ('class_def -> CLASS IDENTIFIER inheritance_opt COLON','class_def',4,'p_class_def','parser.py',61),
  ('inheritance_opt -> LPAREN base_classes RPAREN','inheritance_opt',3,'p_inheritance_opt','parser.py',66),
  ('inheritance_opt -> empty','inheritance_opt',1,'p_inheritance_opt','parser.py',67),
  ('base_classes -> IDENTIFIER base_class_tail','base_classes',2,'p_base_classes','parser.py',74),
  ('base_class_tail -> COMMA IDENTIFIER base_class_tail','base_class_tail',3,'p_base_class_tail','parser.py',78),
  ('base_class_tail -> empty','base_class_tail',1,'p_base_class_tail','parser.py',79),
  ('misc -> IDENTIFIER','misc',1,'p_misc','parser.py',86),
  ('misc -> OTHER','misc',1,'p_misc','parser.py',87),
  ('empty -> <empty>','empty',0,'p_empty','parser.py',91),
]
